#!/usr/bin/env bash

# fix markdown TOC generated by Markdown all in one vscode extension
# https://regex101.com/r/DJJf2I/1
ShellDoc::fixMarkdownToc() {
  local file="$1"
  local fixMarkdownToc

  fixMarkdownToc="$(
    cat <<'EOF'
.INCLUDE "${ORIGINAL_TEMPLATE_DIR}/ShellDoc/fixMarkdownToc.awk"
EOF
  )"

  awk -i inplace "${fixMarkdownToc}" "${file}"
}
