#!/usr/bin/env bash

# @description fix markdown TOC generated by Markdown all in one vscode extension
# to make TOC compatible with docsify
# @arg $1 file:String file to fix
# @exitcode 1 if awk fails
# @see https://regex101.com/r/DJJf2I/1
ShellDoc::fixMarkdownToc() {
  local file="$1"
  local fixMarkdownToc

  fixMarkdownToc="$(
    cat <<'EOF'
.INCLUDE "${ORIGINAL_TEMPLATE_DIR}/ShellDoc/fixMarkdownToc.awk"
EOF
  )"

  awk -i inplace "${fixMarkdownToc}" "${file}"
}
