#!/usr/bin/env bash

# Header

Args::defaultHelp() {
  echo "$1"
}

UI::requireColors() {
  echo "colors"
}

# FUNCTIONS

# REQUIRES
UI::requireColors

# @require UI::requireColors
myFunction() {
  :
}

Args::defaultHelp "Help"
myFunction
