version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["doc/**", "bin/deepsource"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true
  [analyzers.meta]
    dialect = "bash"

[[analyzers]]
name = "docker"
enabled = true
  [analyzers.meta]
    dockerfile_paths = [
      ".docker/Dockerfile.alpine",
      ".docker/Dockerfile.ubuntu",
      ".docker/DockerfileUser"
    ]
