---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CSS
  - HTML
  - SQL
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
EXCLUDED_DIRECTORIES:
  - '.history'
  - '.git'
  - '.idea'
FILTER_REGEX_EXCLUDE: (\.git/|\.history/|\.idea/)
FILEIO_REPORTER: false
PRE_COMMANDS:
  - command: env
    cwd: 'workspace'
POST_COMMANDS:
  # FIX files set as root user
  # HOST_USER_ID and HOST_GROUP_ID set in package.json
  - command: find . -user 0 -exec chown ${HOST_USER_ID}:${HOST_GROUP_ID} {} ';'
    cwd: 'workspace'
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

# Linters configurations
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: (vendor/.*)
BASH_SHELLCHECK_ARGUMENTS: --source-path=/tmp/lint

BASH_SHFMT_ARGUMENTS: -i 2 -ci

CREDENTIALS_SECRETLINT_CONFIG_FILE: .secretlintrc.yml

EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: (\.git)

GIT_GIT_DIFF_PRE_COMMANDS:
  - command: git config --global core.autocrlf input
    continue_if_failed: false
  - command: git config --global core.eol lf
    continue_if_failed: false
  - command: git config --global core.whitespace cr-at-eol,-trailing-space
    continue_if_failed: false

IGNORE_GITIGNORED_FILES: true

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: (report/)

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode/settings\.json|conf/\.vscode/settings\.json|report|.vscode/launch.json)

MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: (report)

SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (\.git/|\.history/|IDE/.*/.idea|.*-megalinter_file_names_cspell.txt|bin/bash-tpl)
SPELL_FILTER_REGEX_EXCLUDE: (\.git/|\.history/|IDE/.*/.idea|bin/bash-tpl)
