---
EXTENDS:
  - .mega-linter.yml
DISABLE_LINTERS:
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - RUBY_RUBOCOP
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - SPELL_VALE
  - SPELL_LYCHEE
  - SPELL_PROSELINT
  # REPOSITORY_TRUFFLEHOG disabled because too slow
  - REPOSITORY_TRUFFLEHOG
  # REPOSITORY_GRYPE disabled because too slow
  - REPOSITORY_GRYPE
