---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        exclude: |
          (?x)^(
            conf\/.vscode\/settings.json
          )$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        exclude: ^vendor/.*$|\.tpl$|^bin/bash-tpl$
        args:
          - --source-path=SCRIPTDIR
          - --external-sources

      - id: shfmt
        args: [-i, '2', -ci]
        exclude: ^vendor/.*$|^tests/data/.*$|^bin/bash-tpl$

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: frameworkLint
        name: frameworkLint
        entry: bash -c './bin/frameworkLint -f plain'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: build-sh-files
        name: build-sh-files
        entry: bash -c './.github/workflows/buildBinFiles --ignore-missing'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: build-doc-files
        name: build-doc-files
        entry: bash -c 'SKIP_BUILD=1 ./bin/doc'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: run-unit-tests
        name: run-unit-tests
        entry: bash -c './bin/test -r src -j 8'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: megalinter
        name: megalinter
        entry: bash -c './bin/megalinter --incremental --fix'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
