---
repos:
  - repo: local
    hooks:
      - id: fixShebangExecutionBit
        name: fixShebangExecutionBit
        entry: bash -c './bin/findShebangFiles chmod +x'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
        exclude: |
          (?x)^(
            pages\/images/.*\.svg|
            images/.*\.svg
          )$
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: forbid-new-submodules
        stages: [commit]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [commit]
      - id: check-json
        exclude: |
          (?x)^(
            .vscode\/settings.json
          )$
        stages: [commit]

  - repo: https://github.com/fchastanet/jumanjihouse-pre-commit-hooks
    rev: 3.0.1
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        exclude: ^vendor/.*$|^tests/data/.*$|^bin/bash-tpl$|\.tpl$
        stages: [commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: ^src/Filters/testsData/
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        stages: [commit]

  - repo: local
    hooks:
      - id: shellcheckLint
        name: shellcheckLint
        entry: bash -c './bin/shellcheckLint --staged -f tty'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [commit]

  - repo: local
    hooks:
      - id: frameworkLint
        name: frameworkLint
        entry: bash -c './bin/frameworkLint -f plain --verbose'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [commit]

  - repo: local
    hooks:
      - id: plantuml
        name: plantuml
        entry: bash -c './bin/plantuml -f png -f svg'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [commit]

  - repo: local
    hooks:
      - id: build-sh-files
        name: build-sh-files
        entry: bash -c './bin/buildBinFiles'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [push]

  - repo: local
    hooks:
      - id: build-doc-files
        name: build-doc-files
        entry: bash -c 'SKIP_BUILD=1 ./bin/doc'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [push]

  - repo: local
    hooks:
      - id: run-unit-tests
        name: run-unit-tests
        entry: bash -c './bin/test -r src -j 30'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [commit]

  - repo: local
    hooks:
      - id: megalinter
        name: megalinter
        entry: bash -c './bin/megalinter --incremental --fix'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true
        stages: [push]
