---
default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^doc/images/.*\.svg$|
            ^doc/guides/Options/generate.*.md$
          )
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        exclude: |
          (?x)(
            ^.vscode\/settings.json$|
            ^.vscode\/launch.json$
          )

  - repo: https://github.com/fchastanet/jumanjihouse-pre-commit-hooks
    rev: 3.0.2
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        exclude: (^vendor/|^manualTests/data/|^bin|\.tpl$|/testsData/)
        stages: [pre-commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: |
          (?x)(
            /testsData/|
            ^doc/guides/Options/generate.*.md$
          )

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^doc/guides/Options/generate.*.md$

  - repo: .
    rev: ac5137e7545099a9d5656884ce5867896144d4ec
    hooks:
      - id: fixShebangExecutionBit
      - id: awkLint
      - id: shellcheckLint
      - id: shellcheckLint
        args: [-f, checkstyle, --xargs]
        pass_filenames: true
        stages: [manual]
      - id: frameworkLinter
        args:
          [
            --expected-warnings-count,
            '72',
            --format,
            plain,
            --theme,
            default-force,
          ]
      - id: plantuml

  - repo: local
    hooks:
      - id: buildShFiles
        name: build sh files
        language: system
        entry: bash -c './bin/buildBinFiles'
        always_run: true
        require_serial: true
        fail_fast: true

      - id: buildDocFiles
        name: build doc files
        language: system
        entry: bash -c 'SKIP_BUILD=1 ./bin/doc --verbose'
        require_serial: true
        always_run: true
        fail_fast: true
        stages: [pre-push, manual]

  # manual stage used to select github action with megalinter full config
  - repo: .
    rev: ac5137e7545099a9d5656884ce5867896144d4ec
    hooks:
      - id: runUnitTests
        stages: [pre-commit]
      - id: megalinterCheckVersion
      - id: megalinter
      - id: megalinterGithubAction
