---
default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^doc/images/.*\.svg$|
            ^doc/guides/Options/generate.*.md$
          )
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        exclude: |
          (?x)(
            ^.vscode\/settings.json$|
            ^.vscode\/launch.json$
          )

  - repo: https://github.com/fchastanet/jumanjihouse-pre-commit-hooks
    rev: 3.0.2
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        exclude: (^vendor/|^manualTests/data/|^bin|\.tpl$|/testsData/)
        stages: [pre-commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: |
          (?x)(
            /testsData/|
            ^doc/guides/Options/generate.*.md$
          )

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^doc/guides/Options/generate.*.md$

  - repo: https://github.com/fchastanet/bash-tools-framework
    rev: 1.1.7
    hooks:
      - id: fixShebangExecutionBit
      - id: fixShebangExecutionBitGithubActions
      - id: awkLint
      - id: shellcheckLint
      - id: shellcheckLintGithubAction
      - id: frameworkLinter
        args:
          [
            --expected-warnings-count,
            '72',
            --format,
            plain,
            --theme,
            default-force,
          ]
      - id: frameworkLinterGithubAction
        args:
          [
            --expected-warnings-count,
            '72',
            --format,
            checkstyle,
            --theme,
            default-force,
          ]
      - id: plantuml
      - id: buildShFiles
      - id: buildShFilesGithubAction

  - repo: local
    hooks:
      - &BUILD_DOC_FILES
        id: buildDocFiles
        name: build doc files
        language: script
        entry: bin/doc
        args: [--verbose, --skip-docker-build]
        pass_filenames: false
        require_serial: true
        always_run: true
        fail_fast: true
        stages: [pre-push]
      - <<: *BUILD_DOC_FILES
        id: buildDocFilesGithubAction
        name: build doc files for Github Actions
        args: [--verbose]
        fail_fast: false
        stages: [manual]

  # manual stage used to select github action with megalinter full config
  - repo: https://github.com/fchastanet/bash-tools-framework
    rev: 1.1.7
    hooks:
      - id: runUnitTests
        # not manual as github will run UT with several versions of bash and arch
        stages: [pre-commit]
      - id: megalinterCheckVersion
      - id: megalinter
      - id: megalinterGithubAction
