- &FIX_SHEBANG_EXECUTION_BIT
  id: fixShebangExecutionBit
  name: fixShebangExecutionBit
  description: |
    Find all files containing a shebang and
    mark them as executable if not yet
  language: script
  entry: bin/findShebangFiles
  args: [chmod, +x]
  pass_filenames: false
  types: ['file', 'shell', 'text']
  always_run: true
  fail_fast: true
  stages: [pre-commit]

- <<: *FIX_SHEBANG_EXECUTION_BIT
  id: fixShebangExecutionBitGithubActions
  name: fixShebangExecutionBit for Github Actions
  fail_fast: false
  stages: [manual]

- &FRAMEWORK_LINTER
  id: frameworkLinter
  name: Bash Framework Linter
  description: |
    Check if your files uses the right syntax
    for using bash-tools-framework
  language: script
  entry: bin/frameworkLint
  args:
    [--expected-warnings-count, '0', --format, plain, --theme, default-force]
  pass_filenames: false
  types: ['executable', 'file', 'shell', 'text']
  always_run: false
  fail_fast: true
  stages: [pre-commit]

- <<: *FRAMEWORK_LINTER
  id: frameworkLinterGithubAction
  name: Bash Framework Linter for Github Actions
  args: [--expected-warnings-count, '0', --format, checkstyle, --theme, noColor]
  fail_fast: false
  stages: [manual]

- id: awkLint
  name: awk Linter
  description: Lint awk files using awk.
  language: script
  entry: bin/awkLint
  args: []
  pass_filenames: false
  files: \.awk$
  always_run: false
  fail_fast: true
  stages: [pre-commit, manual]

- &SHELLCHECKLINT
  id: shellcheckLint
  name: shellcheck Linter
  description: |
    Lint bash files using shellcheck.
    Installing last version automatically
  language: script
  entry: bin/shellcheckLint
  args: [-f, tty, --xargs]
  pass_filenames: true
  files: \.sh$
  types: ['executable', 'file', 'shell', 'text']
  always_run: false
  fail_fast: true
  stages: [pre-commit]

- <<: *SHELLCHECKLINT
  id: shellcheckLintGithubAction
  name: shellcheck Linter for Github Actions
  args: [-f, checkstyle, --xargs]
  fail_fast: false
  stages: [manual]

- id: runUnitTests
  name: Run unit tests
  description: run unit test using bats in docker isolated environment
  language: script
  entry: bin/test
  args: [-r, src, -j, '30']
  pass_filenames: false
  always_run: true
  fail_fast: true
  require_serial: true
  stages: [pre-commit, manual]

- &BUILD_SH_FILES
  id: buildShFiles
  name: build sh files
  entry: bin/buildBinFiles --ignore-missing
  language: script
  pass_filenames: false
  always_run: true
  require_serial: true
  fail_fast: true
  stages: [pre-commit]

- <<: *BUILD_SH_FILES
  id: buildShFilesGithubAction
  name: build sh files for Github Actions
  entry: bin/buildBinFiles
  fail_fast: false
  stages: [manual]

- id: plantuml
  name: Plantuml Converter
  description: Convert plantuml files to images
  language: script
  entry: bin/plantuml
  args: [--same-dir, -f, png, -f, svg]
  pass_filenames: true
  types: ['file', 'non-executable', 'plantuml', 'text']
  always_run: false
  fail_fast: true
  stages: [push, manual]

- id: megalinterCheckVersion
  name: Megalinter Check Version
  description: Megalinter Check if new version is available
  language: script
  entry: bin/megalinter
  args:
    [
      --image,
      'oxsecurity/megalinter-terraform:v7.7.0',
      --check-megalinter-version,
    ]
  pass_filenames: false
  always_run: true
  fail_fast: true
  stages: [pre-push, manual]

- &MEGALINTER
  id: megalinter
  name: Megalinter
  description: use megalinter to check your project
  language: script
  entry: bin/megalinter
  args:
    [
      --image,
      'oxsecurity/megalinter-terraform:v7.7.0',
      --config-file,
      '.mega-linter-light.yml',
      --fix,
    ]
  pass_filenames: false
  require_serial: true
  always_run: true
  fail_fast: true
  verbose: true
  stages: [pre-push]

# manual stage used to select github action with megalinter full config
- <<: *MEGALINTER
  id: megalinterGithubAction
  name: Megalinter for Github Actions
  args:
    [
      --image,
      'oxsecurity/megalinter-terraform:v7.7.0',
      --config-file,
      '.mega-linter-githubAction.yml',
      --fix,
    ]
  stages: [manual]
