---
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, manual]
minimum_pre_commit_version: 3.5.0
fail_fast: true
repos:
  - repo: local
    # this hook is not intended to be run on github
    # it just allows to generate the same pre-commit
    # file with some specific option to github
    hooks:
      - id: preCommitGeneration
        name: preCommitGeneration
        entry: .github/preCommitGeneration.sh
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [pre-commit, pre-push, manual]

  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.21
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, "80", --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-shfmt
          - mdformat-tables
          - mdformat-config
          - mdformat-web
          - mdformat-gfm

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^doc/images/.*\.svg$|
            testsData/.*\.result$
          )
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-yaml
      - id: trailing-whitespace
        exclude: |
          (?x)(
            testsData/
          )
        stages: [pre-commit, pre-push, manual]
      - id: check-added-large-files
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: file-contents-sorter
        files: .cspell/.*\.txt
        args: [--ignore-case]
        stages: [pre-commit, pre-push, manual]
      - id: check-json
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)(
            .vscode\/.*\.json$
          )

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint
        stages: [pre-commit, pre-push, manual]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --dictionary
          - "-"
          - --dictionary
          - .cspell/codespellrc-dic.txt
          - --ignore-words
          - .cspell/codespellrc-ignore.txt
          - --quiet-level
          - "2"
          - --interactive
          - "0"
          - --check-filenames
          - --check-hidden
          - --write-changes
        exclude: >
          (?x)(
              ^installScripts/|
              ^bin/|
              ^install$|
              ^distro$|
              ^srcAlt|
              ^.cspell/codespellrc-.*.txt$
          )

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.4.2
    hooks:
      - id: prettier
        args: [--cache]
        exclude: |
          (?x)(
            \.md$|
            \.vscode/.*\.json$|
            ^\.vscode/.*\.code-snippets$
          )

  - repo: https://github.com/fchastanet/jumanjihouse-pre-commit-hooks
    rev: 3.0.2
    hooks:
      - id: shfmt
        args: [-i, "2", -ci]
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)(
            ^vendor/|
            ^bin/|
            ^manualTests/data/|
            /testsData/
          )

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)(
            /testsData/
          )

  - repo: https://github.com/fchastanet/bash-tools-framework
    rev: 6.1.1
    hooks:
      - id: fixShebangExecutionBit
      - id: awkLint
      - id: shellcheckLint
      - id: shellcheckLintGithubAction
      - id: frameworkLint
        args:
          [
            --expected-warnings-count,
            "62",
            --format,
            plain,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: frameworkLintGithubAction
        args:
          [
            --expected-warnings-count,
            "62",
            --format,
            checkstyle,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: plantuml
        args: [--same-dir, -f, png, -f, svg, --limit-size, "900"]

  - repo: local
    hooks:
      - id: buildDocFilesForGithubActions
        name: build doc files for github actions
        language: script
        entry: bin/doc
        args: [--verbose, --ci]
        pass_filenames: false
        require_serial: true
        stages: [] # GITHUB

  - repo: https://github.com/fchastanet/bash-compiler
    rev: 3.1.3
    hooks:
      - id: buildBashBinaries
