---
rules:
  - id: '@secretlint/secretlint-rule-preset-recommend'
    rules:
      - id: '@secretlint/secretlint-rule-aws'
        options:
          allows:
            - '123456789012' # conf/zsh_profile/.p10k.zsh example
