@startuml "compilerImplementDirective"
title compiler implement interface
skinparam {
  ' https://github.com/plantuml/plantuml/blob/49115dfc7d4156961e5b49a81c09b474daa79823/src/net/sourceforge/plantuml/style/FromSkinparamToStyle.java#L145
  activityDiamondBackgroundColor #AAAAAA
  activityEndColor #red
}
start

:compile scriptFile (implement directive phase);
note right: this phase occurs when the scriptFile has been entirely compiled

partition Compiler::Implement::interface #LightGray {

  #SpringGreen: Compiler::Implement::interface scriptFile;

  partition Compiler::Implement::interfaces #LightSkyBlue {
    #SpringGreen:Compiler::Implement::filter scriptFile;
    while (implementDirective?) is (<color:green>implement directive found)
      -[#green]->
        #SpringGreen:Compiler::Implement::parse $implementDirective
          ~~uses Compiler::Implement::assertInterface~~
        ;
        if (implement directive can be parsed?) is (<color:green>valid directive) then
          -[#green]->
        else (<color:red>invalid implement\n<color:red>directive)
          -[#red]->
          end
        endif
        #SpringGreen:add interfaceFunction to interfaces list;
        -[#green]->
    endwhile (no more implement directive to process)

  }
  #SpringGreen:Compiler::Implement::mergeInterfacesFunctions interfacesList;

  #SpringGreen:Compiler::Implement::validateInterfaceFunctions scriptFile interfaceFunctions;
  if (one function cannot be found in scriptFile?) is (<color:red>missing function\n<color:red>#functionName) then
    -[#red]->
    end
  else
    -[#green]->
  endif
  -[#green]->
  #SpringGreen:All functions of interfaces have been implemented;
}

:Output result;

stop
@enduml
