@startuml "compilerEmbedInjection"
title compiler embed injection
skinparam {
  ' https://github.com/plantuml/plantuml/blob/49115dfc7d4156961e5b49a81c09b474daa79823/src/net/sourceforge/plantuml/style/FromSkinparamToStyle.java#L145
  activityDiamondBackgroundColor #AAAAAA
  activityEndColor #red
}
start

:compiler;

#SpringGreen:Embed::injectIncludes fromFile;

#SpringGreen:Embed::filterIncludes fromFile;
while (include?) is (<color:green>include found)
  -[#green]->
  partition Embed::include #SpringGreen {
    #SpringGreen:Embed::parseInclude $include
      ~~uses Embed::assertAsName~~
      ~~uses Embed::assertResource~~
    ;
    if (include directive can be parsed?) is (<color:green>valid directive) then
      -[#green]->
    else (<color:red>invalid include directive)
      -[#red]->
      end
    endif
    -[#green]->
  }

  if (include name already injected?) then (yes)
    :display skip;
  elseif (include resources already injected?) then (yes)
    :display warning;
  else (<color:green>embed can be included)
    -[#green]->
    partition Embed::include #LightGray {
      #SpringGreen:__Embed::include__ **$resource** **$asName**;
      switch (resource type?)
      case ( resource is a file )
        #SpringGreen:Embed::includeFile;
      case ( resource is a directory )
        #SpringGreen:Embed::includeDir;
      case ( resource is a bash framework function )
        #SpringGreen:Embed::includeFrameworkFunction;
        #SpringGreen:bin/compile;
      case ( error )
        -[#red]->
        end
      endswitch
    }
    if (include success ?) then
      -[#green]->
    else
      -[#red]-> <color:red>display error\n<color:red>and return 2;
      end
    endif
    -[#green]->
  endif

endwhile (no more include to process)

:Output result;

stop
@enduml
