name: Build and Deploy Documentation

on:
  push:
    branches: [master]
    paths:
      - 'content/**'
      - 'static/**'
      - 'configs/site-config.yaml'
      - 'assets/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: fchastanet/my-documents/.github/workflows/build-site-action.yml@master
    with:
      site-name: 'bash-tools-framework'
      baseURL: 'https://fchastanet.github.io/bash-tools-framework'
      checkout-repo: 'fchastanet/bash-tools-framework'
    permissions:
      contents: read
      pages: write
      id-token: write
