---
# Lint the code base and launch unit test at each push or pull request
name: Lint and test
on: # yamllint disable-line rule:truthy
  push:
    # execute when pushing only branches, not tags
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # needed by ouzi-dev/commit-status-updater@v2
      statuses: write
    strategy:
      fail-fast: true
      matrix:
        vendor:
          - ubuntu
          - alpine
        bashTarVersion:
          - '4.4'
          - '5.0'
          - '5.1'
        include:
          - vendor: ubuntu
            bashImage: ubuntu:20.04
            batsOptions: -j 30
            bashTarVersion: 4.4
            runPrecommitTests: false
          - vendor: ubuntu
            bashImage: ubuntu:20.04
            bashTarVersion: 5.0
            batsOptions: -j 30
            runPrecommitTests: false
          - vendor: ubuntu
            bashImage: ubuntu:20.04
            bashTarVersion: 5.1
            batsOptions: -j 30
            runPrecommitTests: true
          - vendor: alpine
            bashTarVersion: 4.4
            bashImage: amd64/bash:4.4-alpine3.18
            batsOptions: -j 30
            runPrecommitTests: false
          - vendor: alpine
            bashTarVersion: 5.0
            bashImage: amd64/bash:5.0-alpine3.18
            batsOptions: -j 30
            runPrecommitTests: false
          - vendor: alpine
            bashTarVersion: 5.1
            bashImage: amd64/bash:5.1-alpine3.18
            batsOptions: -j 30
            runPrecommitTests: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: build bash-tools-${{matrix.vendor}}-${{matrix.bashTarVersion}}
          status: pending

      - name: Pull/Build/Push docker image
        env:
          BRANCH: ${GITHUB_REF##*/}
        run: |
          ./bin/buildPushDockerImage \
            --vendor "${{ matrix.vendor }}" \
            --bash-version "${{ matrix.bashTarVersion }}" \
            --bash-base-image "${{ matrix.bashImage }}" \
            --branch-name "${GITHUB_REF##*/}" \
            --push -vvv

      - name: Check image
        run: |
          docker run --rm \
            "build:bash-tools-${{ matrix.vendor }}-${{ matrix.bashTarVersion }}" bash \
            --version

      # only if pre-commit
      - name: Set up Python
        if: matrix.runPrecommitTests
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install pre-commit
        if: matrix.runPrecommitTests
        run: pip install pre-commit

      - uses: ouzi-dev/commit-status-updater@v2
        if: matrix.runPrecommitTests
        with:
          name: lint
          status: pending

      - name: Run pre-commit
        if: matrix.runPrecommitTests
        run: pre-commit run -a --hook-stage manual

      - name: Archive results
        if: matrix.runPrecommitTests && always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: linter-reports
          path: |
            megalinter-reports/**

      - uses: crazy-max/ghaction-import-gpg@v5
        if: matrix.runPrecommitTests && always()
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: tibdex/github-app-token@v1
        if: matrix.runPrecommitTests && always()
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        if: matrix.runPrecommitTests && failure()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          committer: fchastanet <fchastanet@gmail.com>
          branch: update/pre-commit-fixes
          title: lint fixes
          commit-message: Auto-update lint fixes
          body: |
            some auto fixes have been generated during pre-commit run
          labels: updates

      - uses: ouzi-dev/commit-status-updater@v2
        if: matrix.runPrecommitTests && always()
        with:
          name: lint
          status: ${{ job.status }}

      # Run unit tests
      - name: run unit tests
        run: |
          chmod -R 777 logs
          # shellcheck disable=SC2266
          USER_ID=1000 \
          GROUP_ID=1000 \
          ./bin/test \
            -vvv \
            --vendor "${{matrix.vendor}}" \
            --bash-version "${{matrix.bashTarVersion}}" \
            --bash-base-image "${{matrix.bashImage}}" \
            --branch-name "${GITHUB_REF##*/}" \
            ${{matrix.batsOptions}} \
            --formatter junit -o logs -r src --ci |
            tee "logs/junit-${{github.job}}.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/junit-${{github.job}}.xml'

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results ${{matrix.vendor}} ${{matrix.bashTarVersion}}
          path: '**/junit-${{github.job}}.xml'

      - uses: ouzi-dev/commit-status-updater@v2
        if: always()
        with:
          name: build bash-tools-${{matrix.vendor}}-${{matrix.bashTarVersion}}
          status: ${{ job.status }}

  publishTestResults:
    name: 'Publish Tests Results'
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      checks: write

      # needed by ouzi-dev/commit-status-updater@v2
      statuses: write

      # only needed unless run with comment_mode: off
      pull-requests: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Checkstyle aggregation
        uses: lcollins/checkstyle-github-action@v2.0.0
        with:
          path: '**/junit-*.xml'

      # run this action to get the workflow conclusion
      # You can get the conclusion via env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v3

      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: build
          # neutral, success, skipped, cancelled, timed_out, action_required, failure
          status: ${{ env.WORKFLOW_CONCLUSION }}
